export { TextingIcon } from './TextingIcon'
export { UserIcon } from './UserIcon'
export { ComeBackIcon } from './ComeBackIcon'
export { AdvanceIcon } from './AdvanceIcon'
export { CloseIcon } from './CloseIcon'